### ISSUE TITLE
Galleri lightbox

### ISSUE THREAD

**Issue by neic** [TK-IT/web#10]
`yoxview` mangler. Er det overhovedet det lightbox framework vi skal bruge?

**Comment by furt11** [comment]
Jeg har skrevet at lille pænt alternativ til et eksternt lightbox-script. Når jeg lige får skrevet et passende django-view, så smider jeg det på github.

**Comment by furt11** [comment]
Et flatpage-eksempel på en side med flere billede/video, der benytter tkgal.js-scriptet kan findes her: https://gist.github.com/furt11/dfdd0dad6bf72db764c4

**Comment by neic** [comment]
Venter på #13

**Comment by furt11** [comment]
Galleriet kører nu. Der kunne godt tilføjes lidt javascript(jquery) registrering af horisontalt swipe. Det vil være meget brugbart på mobiler! 

jQuery mobile har swipe events; https://api.jquerymobile.com/swipeleft/ f.eks. Men så skal vi loade endnu et javascript framework udover jquery.

**Comment by neic** [comment]
Jeg lukker det her issue. Jeg har oprettet #22 Swipe i galleri.
