### ISSUE TITLE
Album admin er langsom at indlæse

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#101]
Når jeg tilgår https://beta.tket.dk/admin/gallery/album/5414/ tager det 70 sekunder at indlæse siden! Ifølge FX Developer tools er det 69404 ms "Waiting", dvs. tid brugt på serveren. Er der mon nogle queries der skal optimeres?

**Comment by martinsand** [comment]
Det tager under 4s for mig at loade siden helt. Men jeg ved ikke, om det er
fra cache fra da du tilgik siden første gang. Det har jeg ikke forstand på
;)

tor. 15. sep. 2016 kl. 11.32 skrev Mathias Rav <notifications@github.com>:

**Comment by Mortal** [comment]
Aha, det er kun første indlæsning der tager så lang tid. Måske genererer den thumbnails eller sådan noget? Lukker dette issue...
