### ISSUE TITLE
Forkert placering af billeder i Webkit-baserede browsere

### ISSUE THREAD

**Issue by muldvang** [TK-IT/web#102]
Galleriet virker fint med piletaster, swipe osv., men billederne sidder lidt lavt i Webkit-baserede browsere. Jeg har testet i følgende browsere og problemet opstår i dem alle.

- Safari, iPhone 4S, iOS 7
- Samsungs browser, Galaxy S4 mini, Android 4.4
- Dolphin, Android 4.4
- surf, Linux
- qutebrowser, Linux

Screenshot fra qutebrowser:
![screenshot from 2016-09-16 19-48-56](https://cloud.githubusercontent.com/assets/205164/18595819/a9e0cdf2-7c46-11e6-8e54-51765f8d27a2.png)

**Comment by Mortal** [comment]
Debugget med "Inspect element" i surf. Årsagen er at Webkit ikke genkender CSS `transform` uden `-webkit-`-præfiks; med andre ord mangler `#tkgal-container .lg-file-download, #tkgal-container audio, #tkgal-container img, #tkgal-container video` en `-webkit-transform` property.

Det skal fikses i customstyle.less linje 160. Der er også andre `transform` properties i customstyle.less der mangler en præfikset version.

**Comment by neic** [comment]
@Mortal siger at det virker i surf. Jeg lukker issuet, @muldvang du må genåbne hvis det stadig er et problem.
