### ISSUE TITLE
Permissions på email form

### ISSUE THREAD

**Issue by neic** [TK-IT/web#110]
Permissions til email formen optræder ikke på listen over de tilgængelige. Man kan kun bruge den hvis man er superbruger.
(FORM er nu superbruger)

**Comment by Mortal** [comment]
For at bruge Django permissions skal man have en ContentType, som man kun får automatisk når man har en model. Appen mailinglist har ikke nogen modeller, så den har som standard ingen ContentType. Et workaround er at [lave en dummy ContentType og så binde en ny Permission op på dén](http://stackoverflow.com/a/13933002/1570972).

Jeg har lavet en ny ContentType og Permission:

```
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission
ct = ContentType.objects.create(app_label='mailinglist', model='dummy')
p = Permission.objects.create(content_type=ct, name='Send email', codename='send')
```

Muligvis vil djangoadmin.py spørge om denne "stale ContentType" skal fjernes næste gang vi kører migrate. Den skal naturligvis ikke fjernes.

Jeg har oprettet en "Send email"-gruppe og tilføjet ovenstående Permission til dén, og tilføjet FORM til "Send email"-gruppen (og fjernet hans superbruger-adgang).

Jeg har testet med en ny bruger der kun har "Send email"-gruppen, og denne bruger kan fint tilgå `/email/`, så det virker så vidt jeg kan se.

**Comment by Mortal** [comment]
Og i øvrigt mener jeg at dette er en fin løsning når denne emailformular bare er en midlertidig løsning indtil vi implementerer #108.
