### ISSUE TITLE
Den sidste uges billeder

### ISSUE THREAD

**Issue by neic** [TK-IT/web#114]
De sidste billeder der blev tilføjet til den gamle hjemmeside før GF er ikke kommet med. Eks. siger PR at der mangler to plakater.

**Comment by Mortal** [comment]
Jeg har rsync'et billeder til prodekanus:/Pictures/rav og kørt import-gallery-directory.py for at importere 2015-47-Haengermorgenmad  2015-48-Dekanvelkomst  2015-49-SOEOEL  2015-50-Rushyg  2015-51-Foredrag_med_Bonderoeven.
