### ISSUE TITLE
Zoom i galleri

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#121]
Når man pinch-zoomer i galleriet på mobile, så er navigationsbaren i vejen. Desuden kan man ikke panne da touch events bliver slugt til at håndtere swipe.

Mon ikke der findes en mere full fledged gallery JS app man kan bruge? Det burde være muligt at lave en god UX i moderne smartphone browsers. Ellers bør vi måske slå pinch to zoom fra i galleriet.

**Comment by martinsand** [comment]
Jeg havde på et tidspunkt sat navbar på gallerisiden til at følge siden og
ikke være fastsat. Det fiksede netop dette problem. Jeg ved ikke hvornår
det er blevet fjernet igen.

/FURT

søn. 16. okt. 2016 kl. 13.21 skrev Mathias Rav <notifications@github.com>:
