### ISSUE TITLE
J50 deltagerliste mangler

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#122]

**Comment by neic** [comment]
Ifølge https://github.com/TK-IT/web/issues/88#issuecomment-246183741 besluttede jeg at listen ikke gav mening fordi dataene ikke var rigtige alligevel.

**Comment by neic** [comment]
Ping @Mortal

**Comment by Mortal** [comment]
Det er fint at den er 410 Gone, men så bør den fjernes fra Jubilæums-menuen. Ingen af de andre J50-ressourcer giver fejl.

**Comment by neic** [comment]
Jeg havde ikke set at der var et link til den. Det er fikset.
