### ISSUE TITLE
Old urls are not working - should they?

### ISSUE THREAD

**Issue by MadsBaggesen** [TK-IT/web#124]
Facebook "old stuff on this date" showed me this URL - but it doesn't work anymore.

[https://www.taagekammeret.dk/Billeder/ShowPicture.php?folder=12-0809%252F92-Loebesedler&pic_file=2akv19.jpg&pic_count=43&mainfoldernr=12](https://www.taagekammeret.dk/Billeder/ShowPicture.php?folder=12-0809%252F92-Loebesedler&pic_file=2akv19.jpg&pic_count=43&mainfoldernr=12)

Is that by design/decision, or an error in an re-mapping of old urls?

**Comment by neic** [comment]
Nej. Det er en fejl. Jeg kigger på det.

**Comment by neic** [comment]
Problemet er at i `folder=12-0809%252F92-Loebesedler` er `/` dobbelt encoded som `%252F`. 🤦
