### ISSUE TITLE
Django-jfu er ikke kompatibel med django>1.8

### ISSUE THREAD

**Issue by neic** [TK-IT/web#125]
Template engine [er lavet om](https://docs.djangoproject.com/en/1.10/releases/1.8/#multiple-template-engines). Bla. er `context_processors` [blev flyttet](https://docs.djangoproject.com/en/1.10/releases/1.8/#django-core-context-processors).

[Django-JFU](https://github.com/Alem/django-jfu/) er ikke blevet opdateret siden april 2015. Der er et [pull request](https://github.com/Alem/django-jfu/pull/36), men det er ikke merged. Vi kan tilføje
`git+https://github.com/CalPolyResDev/django-jfu` til `requirements.txt` for at bruge det. Det ser ud til at virke, men er ikke særligt fremtidsikret. Måske skal vi finde en anden løsning end Django-JFU.

**Comment by Mortal** [comment]
Jeg synes godt vi kan vedligeholde en fork af django-jfu eller bare pege på CalPolyResDev. Det er en lille komponent og den fungerer så vidt jeg ved fint nok i praksis.
