### ISSUE TITLE
Opdater J60

### ISSUE THREAD

**Issue by neic** [TK-IT/web#128]
FUHR skriver:

- [x] Vi laver et resume, i stil med det fra J60, som vi snart sender.
- [x] I må gerne lægge jubilæumsskrift og sangbog ind (vedhæftet her).
- [x] Under menupunktet jubilære: Kald "J60" siden for "Arrangementer" og ændr overskriften (i teksten) til "Arrangementer i forbindelse med J60". Overvej at ændre fremtid til fortid ("Der skal afholdes" til "Der blev afholdt" og så fremdeles).
- [x] Overvej at linke til albummet om J50 fra jubilæumsmenuen ...
- [x] - og det samme, når der engang kommer billeder fra J60. Det er protokol-gruppen, der sorterer billeder. :)

**Comment by Mortal** [comment]
Jeg har indsat J60koors resume på https://www.taagekammeret.dk/J60/ og flyttet den gamle J60 flatpage til https://www.taagekammeret.dk/J60/invitation/ og opdateret https://www.taagekammeret.dk/jubi/.
