### ISSUE TITLE
Album order

### ISSUE THREAD

**Issue by neic** [TK-IT/web#13]
Lav albummodellen om:
- Fjern order
- Tilføj date
- Tilføj 'Årets gang'

**Comment by furt11** [comment]
Hvad med om vi tilføjede en dato til albums og blot sorterer efter denne? 
For det tilfælde at dato er angivet til blot årstallet, så er det et generelt album ala 'løbesedler', 'plakater', osv. tilhørende bestyrelsesperioden med gf i det år. 

Det gør 'order' og 'gfyear' overflødig for albums, da man vel altid enten vil sortere albums kronologisk efter dato eller alfabetisk efter albumtitel. 

Hvad tænker I?

**Comment by neic** [comment]
Det giver god mening. Jeg tror dog stadig at vi skal have et gfyear: hvis vi gemmer datoen for hvornår en given bestperiode starter og slutter et andet sted og gruppere efter det, kommer KBEST album osv ikke i de rigtige år uden at give dem en falsk dato. Et gfyear kan sættes rigtigt automatisk det meste af tiden og folk kan nemt gennemskue at det er det de skal ændre når albummet ikke dukker op det rigtige sted.

Istedet for at have magiske input til 'Årets gang', vil en bool være mere transparent.

Når vi migrere gamle data må vi opfinde falske datoer i den rigtige rækkefølge.

**Comment by furt11** [comment]
Jeg forsøger at tilføje dato-felt, boolean, og slug til modellen for album ;)

**Comment by furt11** [comment]
Album order er fixed nu. Der inddeles i gfyear, dernæst eventalbum og til slut publish_date. Nuværende gfyear er expanded fra start
