### ISSUE TITLE
Jubilæumsmenuen er lang

### ISSUE THREAD

**Issue by neic** [TK-IT/web#130]
Dropdown menuen Jubilæer er lang efterhånden. Da den blev lavet var der ~8 punkter, nu er der 19. Man skal scrolle langt på små skærme og det er svært at have et overblik.

Submenuer er ikke gode til små skærme [og findes ikke i Bootstrap 3 af den grund](https://github.com/twbs/bootstrap/pull/6342#issuecomment-11594010).

En mulig løsning er at lave en Jubilæumsside med en kort tekst, evt et billede samt links til alle ressourcerne for de 3 jubilæer.

Dette kunne løses samtidig med #95 Nyt indhold.

**Comment by martinsand** [comment]
Det bliver helt naturligt skåret ned igen, så snart der kommer en J60-sammenfatning, som kan linke til dokumenter og galleri-sider. Jeg ved ikke om J60-koor selv sammenfatter noget, eller om det lægges på #95 , som du foreslår.

**Comment by neic** [comment]
Det gør de ifølge #128. Det gør dog J60 mindre synligt end J40 og J50 da de har link til diverse dokumenter og billeder fra menuen. Der for var mit forslag at lave en side med <10 linjer tekst fra hver jubilæum, en liste af links (inklusiv et til sammenfatningen) og måske et billede.
