### ISSUE TITLE
32x32 favicon

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#132]
De fleste websites bruger 32x32 eller 48x48 ikoner som /favicon.ico, men vores nuværende er 16x16. Selvom sidens markup angiver PNG-billeder i større formater, bruger Firefox det "forkerte":

![favicons](https://cloud.githubusercontent.com/assets/373639/23067106/b4c7685c-f4eb-11e6-8a41-1930b439033e.png)

Wikipedia forklarer det under tabellen "How to use": https://en.wikipedia.org/wiki/Favicon#How_to_use

**Comment by martinsand** [comment]
Hvis problemet ifølge wiki-siden er, at Firefox bruger det sidste "favicon"-tag og vores sidste ikon-tag med `rel="icon"` er en png med 16x16 opløsning, så er det vel bare at tilføje endnu et tag til sidst:
`<link rel="icon" href="{{ STATIC_URL }}favicon/favicon.ico">`
Ovenstående vil give mening, hvis Firefox kun kigger efter det sidste tag med `rel="icon"`. Det er ikke særlig godt formuleret på wiki-siden.

I `favicon.ico`-filen er der jo både 16x16, 32x32 og 48x48 opløste ikoner, som Firefox nok så vælger den rigtige af, så længe det er den fil, den loader(fordi det er det sidste tag med `rel="icon"`). Kan nogen med Firefox prøve det af?

**Comment by martinsand** [comment]
Min foreslåede ændring kan ses i #133 .

**Comment by Mortal** [comment]
favicon.ico er 16x16. Jeg vil mene løsningen er at lave et favicon.ico i 32x32.

**Comment by martinsand** [comment]
.ico-filer kan indeholde flere opløsninger. Jeg tog bare
https://realfavicongenerator.net/favicon_checker?protocol=https&site=TAAGEKAMMERET.dk
for
gode varer. Den mener at vores .ico-fil indeholder alle relevante
opløsninger.

fre. 17. feb. 2017 kl. 15.26 skrev Mathias Rav <notifications@github.com>:

**Comment by Mortal** [comment]
Hmm... Måske er problemet at Firefox foretrækker ikonet med den højeste farvedybde? 16x16-ikonet er 32-bit hvorimod 32x32 og 48x48 er 8-bit (palette?).

Hvis jeg sammenligner med et favicon fra StackExchange, så lader den eneste væsentligste forskel til at være at farvedybderne for SE-ikonet alle er ens, hvorimod de er forskellige for vores ikon.

```
rav@pictoris:~/Downloads$ wget https://www.taagekammeret.dk/static/favicon/favicon.ico
rav@pictoris:~/Downloads$ identify favicon.ico 
favicon.ico[0] ICO 16x16 16x16+0+0 32-bit sRGB 7.15KB 0.000u 0:00.010
favicon.ico[1] ICO 32x32 32x32+0+0 8-bit sRGB 7.15KB 0.000u 0:00.020
favicon.ico[2] ICO 48x48 48x48+0+0 8-bit sRGB 7.15KB 0.000u 0:00.010
rav@pictoris:~/Downloads$ wget -O se.ico https://cdn.sstatic.net/Sites/webapps/img/favicon.ico
rav@pictoris:~/Downloads$ identify se.ico 
se.ico[0] ICO 16x16 16x16+0+0 32-bit sRGB 5.43KB 0.000u 0:00.000
se.ico[1] ICO 32x32 32x32+0+0 32-bit sRGB 5.43KB 0.000u 0:00.000
```

**Comment by martinsand** [comment]
Jeg tænker stadig at det er fordi den henter billeder fra det sidste
htmltag med rel="icon". En ombytning af rækkefølgen af vores tags, eller
tilføjelsen af ny(mit forslag), ville fikse det.
Vil du prøve det af?

Det kan være du har ret med farvedybden. Hvorfor er de lavet sort-hvide -
for at spare plads?

fre. 17. feb. 2017 kl. 15.34 skrev Mathias Rav <notifications@github.com>:

**Comment by Mortal** [comment]
Jeg har testet #133 i production. Det gør ingen forskel.

Desuden er der allerede et rel="shortcut icon" længere nede i favicon.html som jeg tror er synonymt med rel="icon"?
