### ISSUE TITLE
Skift font på siden?

### ISSUE THREAD

**Issue by martinsand** [TK-IT/web#134]
Jeg synes sku ikke Helvetice Neue og afarter deraf passser så godt på siden. Jeg foreslår en font som eksempelvis 'Lekton' - som er at finde i googles font-api til fri benyttelse. Jeg kan godt lide monospace når nu skrivemaskiner og kode er en del af TKs identitet. 

Lekton:
<img width="894" alt="lekton" src="https://cloud.githubusercontent.com/assets/15422159/23557416/4c0c55b6-0030-11e7-8120-75ca1bd77358.PNG">,

som jeg finder mere letlæselig end den mere traditionelle Courier New:
<img width="882" alt="courier new" src="https://cloud.githubusercontent.com/assets/15422159/23557417/4c0eb504-0030-11e7-8c74-4ec064a893f7.PNG">

Hvad tænker I? Har I andre ideer til font-valg?

**Comment by Mortal** [comment]
Hvordan ser Helvetica Neue ud? I min browser er det Nimbus Sans (systemets sans-serif) der bruges.

Jeg er personligt ikke stor fan af web fonts pga. tilhørende ["flash of invisible text"](https://css-tricks.com/fout-foit-foft/) ved load.

**Comment by martinsand** [comment]
Helvetica Neue:
<img width="884" alt="helvetica neue" src="https://cloud.githubusercontent.com/assets/15422159/23602246/f0ca97cc-024f-11e7-969c-35bdee0fbb89.PNG">

Er FOIT virkelig et større problem? Er det ikke kun indtil browseren har cached den font?

**Comment by neic** [comment]
Vi henter allerede Computer Modern til logoet. CSS-klassen ` tk-brand` har [`font-family: 'Computer Modern Typewriter','Courier New',Courier,monospace;`](https://github.com/TK-IT/web/blob/master/static-src/customstyle.less#L49). De ligger i [static-src/cmun](https://github.com/TK-IT/web/tree/master/static-src/cmun). Vi skal ikke have mere end en slab serif skrivemaskine-ligende font på siden.

Helvetica Neue bliver sat som en del af `@font-family-sans-serif:  "Helvetica Neue", Helvetica, Arial, sans-serif;` i [`static-src/bootstrap/less/variables.less`](https://github.com/twbs/bootstrap/blob/81df608a40bf0629a1dc08e584849bb1e43e0b7a/less/variables.less#L45). Det er alle systemfonte på forskellige styresystemer. Ideen med den linje er at siden ser nogenlunde ens ud på alle systemer, uden der ikke er noget FOIT.

Jeg syntes ikke at vi skal have en skrivemaskine-ligende font på `body`. Det er bliver for visuelt tungt. For meget af det gode. En simpel Helvetica (-klon) er rent. Let brug af Computer Modern og hoppe-danse når vi skriver TÅGEKAMMERET gør siden unik.

**Comment by neic** [comment]
Se desuden også #48 som omhandler ændrigen væk fra en anden slab-serif font fra Google til Computer Modern.

**Comment by Mortal** [comment]
Ang. "Er det ikke kun indtil browseren har cached den font?":

Jeg synes vi skal optimere det første besøg til siden. Hvis fonten er cached, så er det fordi den besøgende er blevet overbevist om at besøge siden efter sit første besøg. Hvis det første besøg giver et dårligt indtryk, så er det mindre sandsynligt at den besøgende kommer igen (og så hjælper cachen os ikke).

**Comment by neic** [comment]
Jeg lukker det her. Hvis der stadig er holdninger der ikke er blevet hørt, må det genåbnes.
