### ISSUE TITLE
Facebook preview

### ISSUE THREAD

**Issue by neic** [TK-IT/web#146]
Der mangler et facebook preview når man linker direkte til et billede eller til et album.

**Comment by martinsand** [comment]
Det fungerer vist allerede fint? @neic 
Jeg lukker den i hvertfald.

Test opslag, der efter min opfattelse læses korrekt af facebook:
<img width="386" alt="capture" src="https://user-images.githubusercontent.com/15422159/31851496-3cc733e4-b667-11e7-895a-a52162c80456.PNG">
