### ISSUE TITLE
Billede datetime fra exif

### ISSUE THREAD

**Issue by neic** [TK-IT/web#15]
For at billederne bliver sorteret rigtigt burde vi sortere efter `Exif.Image.DateTimeOriginal` med fallback til `Exif.Image.DateTime`.

Vi kan også bruge datane til at lave slugs. Se #14.

**Comment by furt11** [comment]
Kan vi lave dem unikke for god ordens skyld? Så f.eks. hvis der allerede findes et billede med samme timestamp ned til sekundet, så tilføjes blot sekund til? 
Men ellers lyder det perfekt.

**Comment by neic** [comment]
Nej. Det sker tit at der bliver tage flere billeder i sekundet. Der findes `Exif.Image.SubsecTimeOriginal` og `Exif.Image.SubsecTime`. Måske kan de bruges. Der er sikkert et bibliotek der tager sig af det hele.

Det er ikke en opgave for `DateTimeField` at være unik. Se også [`unique_for_date`](https://docs.djangoproject.com/en/1.8/ref/models/fields/#unique-for-date).
