### ISSUE TITLE
Billeder slettes ikke

### ISSUE THREAD

**Issue by Hogfeldt** [TK-IT/web#155]
Når man udvælger billeder og bruger slet funktionen, slettes billederne ikke. Det ser ud til at der stadig ligger billeder der står til at blive slettet i albummet fra GF under 17/18.

**Comment by Mortal** [comment]
Problemet var at det er brugeren `www-data` der opretter billederne under `/Pictures/tkammer`, men det er brugeren `tkammer` der kører cronjobbet for at slette billeder. Jeg har rettet ACL for `/Pictures/tkammer` med `setfacl` så `tkammer` nu har skriveadgang til alle nuværende og fremtidige filer og mapper. Nu kører cronjobbet fint, og billederne er slettet.
