### ISSUE TITLE
Viderestil {www.} til {} eller omvendt

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#158]
Lige nu findes den samme hjemmeside på https://www.TAAGEKAMMERET.dk og på https://TAAGEKAMMERET.dk -- det er dumt.

**Comment by neic** [comment]
Jeg har lavet (ahem. fjernet kommenteringen foran) en RewriteRule til at viderestille alting til https://TAAGEKAMMERET.dk. Af en eller anden grund fik jeg enkasseienfestforening.dk certifikatet første gang jeg forbant.

Jeg har også fjernet beta.tket.dk
