### ISSUE TITLE
TK prefix

### ISSUE THREAD

**Issue by neic** [TK-IT/web#163]
Lav en sane måde at bruge `tk_prefix` på i `django-wiki`. Se også #165 for trivielle ting fra `tkbrand`.

**Comment by neic** [comment]
Lige nu er der følgende makroer (med `GFYEAR=2015`) :

```
[tk_prefix 2010]VC        T²OVC
[tk_prefix 2010 VC]       T²OVC
[tk_kprefix 2016]BEST     KBEST
[tk_kprefix 2016 BEST]    KBEST
KA$$[tk_postfix 2017]     KA$$17
[tk_postfix 2017 KASS]    KA$$17
[tk_prepostfix SEKR 2014] GSEKR 2014/15
[tk_email FUHØ 2010]      <FUHOE10@TAAGEKAMMERET.dk> # md hyperlink
```

I `tk_prefix`, `tk_kprefix` og `tk_postfix` er titlen valgfri. I `tk_prepostfix` og `tk_email` er den obligatorisk. Problemet er at rækkefølgen er forskellig i de to grupper. Vi kan:

1. Lade være med at gøre noget. `tk_prepostfix` og `tk_email` bliver nok ikke brugt så tit alligevel.
2. Lave `tk_prepostfix` og `tk_email` om til noget der ligner:
```python
def tk_prepostfix(self, year=None, title='',):
    if title in (None, ''):
        # Skriv en fejl.
    # …
```
3. Ændre rækkefølgen af argumenterne på de andre og gøre `title` obligatorisk.  Det betyder at `[tk_prefix 2010]VC`, som ligner `tket.sty`, ikke virker.

Jeg hælder til 3. Så er der kun en måde at gøre ting på. Jeg tror ikke at forskellen med `tket.sty` bliver et problem.

----
Hvad er formålet med at `_get_year()` har: `if year in (None, ''): return config.GFYEAR`? Jeg vil ikke forvente at `[tk_prefix]` retunerede ingenting uden at give mig en fejlmeddelelse.

----
Ping @Mortal

**Comment by Mortal** [comment]
Jeg er enig i at det er problematisk at rækkefølgen af argumenter er forskellig. Der er en anden løsning:

4. Tillade både `[tk_prefix 16]FORM` og `[tk_prefix FORM16]`. Hvis arg er numerisk, så fortsæt med int(arg) og title=`''`; ellers brug `tk.parse()` til at hente title og year. Brug dette format i alle makroerne; prepostfix og email kræver at title ikke er tom.

Der er ca. 30 steder i BESTeval hvor \KTKprefix bruges uden efterfølgende titel, f.eks. "\KTKprefix{15} bestilte og solgte 350~pølsehorn" i efter-sommerferien.tex, og jeg synes vi skal understøtte den konstruktion.

**Comment by neic** [comment]
Hvis vi vil beholde `[tk_prefix 16]FORM` konstruktionen syntes jeg at 2 er bedere.

Med `tk.parse()` kan vi skrive ting som `[tk_prefix GBEST]` som bliver til `GBEST` hvert år. (Som måske/måske ikke er det man forventer.)

Jeg har i 3d556234438c0f3790d12cea1943f91c941a8d0c tilføjet en fejlmeddelelse som kan bruges.
