### ISSUE TITLE
Fejl i migrations (fredag morgen)

### ISSUE THREAD

**Issue by furt11** [TK-IT/web#17]
Jeg kan ikke selv løse problemet med kombinationen af FUHI's og mine migrations. Nogen, der kan hjælpe?

**Comment by furt11** [comment]
https://www.youtube.com/watch?v=ZSt8JT-A6hw

**Comment by Mortal** [comment]
Jeg kigger på det.

**Comment by furt11** [comment]
Har lige pushet et umiddelbart fix, hvor jeg har fjernet et par migrations og lavet en ny.

**Comment by furt11** [comment]
Nej, det fiksede ikke alt.
