### ISSUE TITLE
/email/ giver 403 i stedet for at viderestille til login

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#181]

**Comment by neic** [comment]
I [`mailinglist/views.py#L15`](https://github.com/TK-IT/web/blob/master/tkweb/apps/mailinglist/views.py#L15) er `raise_exception=True`. Er der nogen grund til det?

```python
send_permission_required = permission_required(
    'mailinglist.send', raise_exception=True)

class EmailFormView(FormView):
    # […] 
    @method_decorator(send_permission_required)
    def dispatch(self, request, *args, **kwargs):
        return super(EmailFormView, self).dispatch(request, *args, **kwargs)
```

**Comment by Mortal** [comment]
Hmm... Jeg kan ikke huske hvorfor jeg har sat raise_exception.

**Comment by Mortal** [comment]
"If the raise_exception parameter is given, the decorator will raise PermissionDenied, prompting the 403 (HTTP Forbidden) view instead of redirecting to the login page." Det lyder som om at løsningen er at fjerne raise_exception.
