### ISSUE TITLE
Eval wiki kan ikke lide græske bogstaver

### ISSUE THREAD

**Issue by neic** [TK-IT/web#199]
`RεmToR` bliver til `R?mToR`. PROPAGANDA har en del tegnsætning også `ε` alene, så en `[remtor]`-makro vil kun løse noget at problemet. 

Når det er løst skal mindst følgende læses igennem:
* `/nf/*`
* `/underforeninger/naestformationen/`

**Comment by Mortal** [comment]
Uden at have undersøgt det nærmere vil jeg tro det skyldes at databasen er i Latin1 og ikke UTF-8. Som workaround kan man bruge HTML entities, dvs. `R&epsilon;mtor`.

**Comment by neic** [comment]
Hvis databasen bliver lavet om skal det være til `utf8mb4` ikke `utf8`. Se: https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

**Comment by Mortal** [comment]
Det er desværre ikke altid muligt at bruge utf8mb4, da visse Django-modeller har VARCHAR(255) søjler, men med utf8mb4 er der problemer når søjlerne er over 192 tegn (dvs. over 768 bytes ved 4 bytes pr. tegn) brede. Jeg tror det er noget man kan omgå ved at pille ved noget ROW_FORMAT eller noget i nogen versioner af MySQL, men generelt er det noget bøvl. utf8 har derimod ikke disse problemer (men utf8 understøtter ikke emoji).

**Comment by neic** [comment]
`[remtor]` og `[eps]` blev implementeret i 81db18a978fc46cb8a60ff29b25dbb7277af3155
