### ISSUE TITLE
Swipe i galleri

### ISSUE THREAD

**Issue by neic** [TK-IT/web#22]
@furt11 skriver i #10 

> Galleriet kører nu. Der kunne godt tilføjes lidt javascript(jquery) registrering af horisontalt swipe. Det vil være meget brugbart på mobiler!

> jQuery mobile har swipe events; https://api.jquerymobile.com/swipeleft/ f.eks. Men så skal vi loade endnu et javascript framework udover jquery.

**Comment by furt11** [comment]
Jeg valget at bruge "touchSwipe" jQuery-plugin, til at registrere swipe. Jeg håber, at det virker på alle enheder, men jeg har kun testet på windows 10 og android.
