### ISSUE TITLE
Hash collision i Imageslug

### ISSUE THREAD

**Issue by neic** [TK-IT/web#23]
Der er ca. 40000 billeder på hjemmesiden nu. Med et hash med 36^6=~2.1e9 muligheder giver det en risiko for en hashcollition på ~37%. Se [wikipedia](https://en.wikipedia.org/wiki/Birthday_attack#Simple_approximation).

Med en `SLUG_SIZE = 9` er risikoen istedet ~0,0008%

**Comment by Tyilo** [comment]
Slugs behøver ikke at være kollisionsfrie med billeder fra andre albums. Så vi antog at max 1000 billeder per album, så kun 0.023 % for kollision.

**Comment by neic** [comment]
`unique=True` er sat på `SlugField`. Det virker for _alle_ instanser af `Image` klassen.

**Comment by Tyilo** [comment]
Det burde nok ændres, da der vel godt kan være præcis det samme billede i flere albums?

**Comment by neic** [comment]
Ja. Der skal også være et andet check i [models.py#L95](https://github.com/TK-IT/web/blob/master/tkweb/apps/gallery/models.py#L95)
