### ISSUE TITLE
Mystisk tidspunkt på ny-uploadede billeder

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#242]
I albummet [Rusdage](https://taagekammeret.dk/admin/gallery/album/5585/change/) (17/18) er tidspunkterne i slug rigtige (dvs. lokaltid), men `date` feltet er 70 minutter foran. Da 70 = 120 - 50 virker det som om der er noget CMT Copenhagen Mean Time (= GMT+0:50:20) korrektion inde over.

**Comment by neic** [comment]
Duplicate af  #104

**Comment by Mortal** [comment]
Ah, tak - jeg troede faktisk vi havde løst det og at problemet var genopstået... Oh well
