### ISSUE TITLE
Billede URL

### ISSUE THREAD

**Issue by neic** [TK-IT/web#28]
I #9 er det blevet diskuteret om billederne skal identificeres med et hash, eller det originale filnavn. Jeg flytter diskussionen her til.

**Comment by neic** [comment]
@furt11 skriver i https://github.com/TK-IT/web/issues/9#issuecomment-155761534
> […] Vi kan måske endda blot bruge filnavne fra de originale billeder (uden jpg) i de nye url'er i stedet for de slugs, som bruges pt., hvis filnavne er unikke for billeder i samme album.

@furt11 skriver i https://github.com/TK-IT/web/issues/9#issuecomment-155763918
> […] Men hvad skal vi vise i url'en?

@Mortal skriver i https://github.com/TK-IT/web/issues/9#issuecomment-155764716
> Det originale filnavn...? Jeg var ikke med til at diskutere det til hackday, så hvis I har noget smartere, er det helt fint med mig.

@furt11 skriver i https://github.com/TK-IT/web/issues/9#issuecomment-155764901
> Altså de originale inkl. ".jpg"? Med store bogstaver, hvad hvis der er mellemrum, fjollede tegn, osv.?

@Mortal skriver i https://github.com/TK-IT/web/issues/9#issuecomment-155781206
> Mellemrum burde ikke være et problem; fjollede tegn burde blive håndteret af Django. Tutorhjemmesiden (som pt. kører Python 2) har problemer med uploads for filnavnet ikke er ASCII (noget med encodings), men det burde ikke være et problem i Python 3.

**Comment by Tyilo** [comment]
Til hackday snakkede vi om at bruge enten `hash-dato-tid` eller `hash` afhængig om datoen kunne findes via exif.

Er de originale filnavne normalt beskrivende eller hedder be bare `XXX_0001.jpg`, `XXX_0002.jpg`, etc.`

**Comment by neic** [comment]
En stikprøve viser alle mulige typer: `DSC_2352.jpg`, `IMG_0012.JPG`, `20150206-202932.jpg`, `hstr2.jpg`, `form.jpg`, `karneval03.jpg` `100_0050.jpg`

**Comment by neic** [comment]
Dette issue blokere for flere ting. Jeg vil gerne have det besluttet.

Her er pro/con som jeg ser det:

**Hash**
:white_check_mark: kort
:x: sortere ikke i korrekt rækkefølge
:x: ingen meningsfyldt information

**Filnavn**
:white_check_mark: sortere i korrekt rækkefølge (med mindre der er billeder fra flere kameraer i albummet)
:x: ingen meningsfyldt information

**Dato**
:white_check_mark: sortere i korrekt rækkefølge
:x: EXIF er kun på de nyeste billeder, så vi skal have en fallback alligevel.

Jeg hælder mest til at bare bruge filnavnet. Det gør det let at følge det samme billede alle steder. URLen til original billedet, URLen til billedesiden og placeringen på filsystemet har allesammen samme opbygning.

Har I nogle indvendinger? @Tyilo @furt11

**Comment by furt11** [comment]
Jeg vil personligt foretrække dato-tidspunkt og benytte filnavn som fallback. Det vil give url'en en _mening_. 

Desuden tror jeg, at der i fremtiden kun bliver flere kameraer til arrangementer, hvorfor at dato-tidspunkt sorteringen vil kunne flette billedserier sammen til et kronologisk album. 

Jeg kan sagtens følge argumentet med overskuelighed i filsystemet. Men rent UX-mæssigt vil jeg nok mene at dato&tid er at foretrække. Jeg vil gladeligt overlade valget til den, der implementerer en løsning.

**Ang. "flere kilder og blandede filnavne"**: Jeg har desuden overvejet muligheden for at tillade upload af billeder, som gæster selv har taget til et arrangement. Det kræver selvfølgelig noget med godkendelse af upload før de vises i albums. Men jeg tror I forstår hvad jeg mener.

**Comment by Tyilo** [comment]
Jeg har ikke noget imod nogen af løsningerne, men jeg er mest enig med @furt11.
