### ISSUE TITLE
jfu/bootstrap og admin interferens

### ISSUE THREAD

**Issue by neic** [TK-IT/web#29]
Jquery-file-upload formen på album `change_form` ændre på knapper og styling fordi den hiver bootstrap ind. Alt efter viewport størrelsen er der er også nogle gange nogle `<div>` der ligger over admin formen, så man ikke kan interagere med elementerne der i.

**Comment by Mortal** [comment]
[CSS to the rescue!](https://developer.mozilla.org/en/docs/Web/HTML/Element/style#A_scoped_stylesheet)
[Nå nej, vent...](http://caniuse.com/#feat=style-scoped)
