### ISSUE TITLE
Python 2-support

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#31]
Eftersom Apache-serveren på prodekanus og på pulerau kun kan have enten mod_python med Python 2 eller mod_python med Python 3, kører vi indtil videre med Python 2 i production, da det er det nemmeste (og fra mit synspunkt det mest stabile) at sætte op.

Derfor bør hjemmesiden være Python 2+3-kompatibel. Heldigvis gør Django det nemt at være, hvis man er opmærksom på det.

**Comment by neic** [comment]
Pr August 2016 kører prodekanus Python 3.
