### ISSUE TITLE
Thumbnail generation er langsom

### ISSUE THREAD

**Issue by neic** [TK-IT/web#33]
En lille test på min MBP med 32 billeder på i alt ~150 MiB viser at det tager det ~30 sekunder at generere alle thumbnails til `album.html` og ~2 minutter at generere til `image.html`. Det er selvfølge kun første load, men den første der besøger siden efter et nyt album er uploadet vil se det. Desuden vil det første upload på >100GB sikkert give problemer.

En mulighed er https://github.com/chhantyal/sorl-thumbnail-async

**Comment by furt11** [comment]
Måske bare lave request til album siden efter at billeder er blevet tilføjet i admin-modulet. Ville det ikke gøre tricket? 
Men ja, måske vi bare skal have celery som en generel løsning til asynkrone opgaver.

**Comment by neic** [comment]
[versatileimagefield](http://django-versatileimagefield.readthedocs.org/en/latest/) ser ud til at kunne det samme som sorl-thubnail + sorl-thumbnail-async og den er, til forskel fra sorl-thubnail-async, under aktiv vedligeholdelse.

Det er desuden integreret med Django REST Framework som vi måske skal bruge i fremtiden. Se #30.
