### ISSUE TITLE
Skaler billedet på image.html så det ikke er større end viewport

### ISSUE THREAD

**Issue by neic** [TK-IT/web#36]
Hvis billedet er højere end viewport kommer der scrollbars. Jeg har prøvet med halvhjertet med ren css, men fik det ikke til at virke. Alternativt burde det være let med js.

**Comment by Tyilo** [comment]
Noget man måske kan gøre med flexbox?

**Comment by neic** [comment]
Det var det jeg prøvede, men fik det ikke til at virke. Jeg prøvede ikke nok til at konstatere at man ikke kunne.

**Comment by Tyilo** [comment]
Dårligt hack der ser ud til at virke: `max-height: calc(100vh - 170px);`
Jeg ved ikke hvor hacky vi ønsker at lave det.

**Comment by furt11** [comment]
Det burde være okay, i hvert fald i de fleste nyere browsere. http://caniuse.com/#feat=viewport-units

**Comment by Tyilo** [comment]
Jeg mente specifikt at `170px` er hardcoded.

**Comment by neic** [comment]
Jeg har falmet mere i blinde med flexbox, men gav til sidst op da der var flere hardcodede variabler end med `max-height: calc(100vh - 170px);`. Problemet med den er dog at den virker ikke på smalle skærme hvor breadcrumbs wrapper til to linjer og/eller `tkgal-crontrols` kommer under breadcrumbs og/eller teksten i footeren wrapper. Det er størst problem med portræt billeder.

Vi kunne dog evt. sørge for at disse elementer også blev skaleret (mere) ned på små skærme.
