### ISSUE TITLE
img med srcset og src loader src uanset om det skal bruges eller ej

### ISSUE THREAD

**Issue by neic** [TK-IT/web#37]
I Chrome 48 på OSX henter `<img srcset="small.jpg 500w, large.jpg 1000w" src="fallback.jpg">` stadig `fallback.jpg` selvom den aldrig bliver brugt. Det betyder at `image.html` loader alle 720px thumbnails selvom de aldrig bliver vist. Jeg ved ikke om det er en bug i vores kode eller i browseren.

**Comment by furt11** [comment]
Hvis det er et udbredt problem at browsere ikke kan finde ud af at begrænse
sig til at hente en version af billedet, så kan vi overveje at ty til
js-løsninger, som f.eks. *https://github.com/aFarkas/respimage
<https://github.com/aFarkas/respimage> *. Der er flere andre kandidater,
men dette var lige den mest lovende af de første tre jeg fandt.

ons. 23. mar. 2016 kl. 23.37 skrev Mathias Dannesbo <
notifications@github.com>:

**Comment by neic** [comment]
Dette fixede @furt11 i eeaf5201e4b879dbd6d436a4f38ae265054d2fe2. Selvfølgelig henter browseren `src=` når der ikke er noget `srcset=` men et `data-srcset=`. 🤦

**Comment by neic** [comment]
Problemet er nu at `src=` required på `<img …>`. Et `<img data-src="…">` er ikke valid HTML.

Jeg er ikke sikker på hvordan vi kan løse det uden at skrive det meste af galleriet om til at hente en `.json`-filliste asynkront.

**Comment by furt11** [comment]
Vi kan tilføje det som en class="class1 class2
slug_12312342423423423423234234232". Så er det bare en mindre ændring af
gallery.html og tkgal.js, der skal til.

tir. 3. maj 2016 kl. 14.55 skrev Mathias Dannesbo <notifications@github.com

**Comment by neic** [comment]
Jeg forstår ikke din løsning, men har lige regnet en ud selv: Vi tilføjer en tom `src` samt en `data-src` med den enlige sti. Så kan `tkgal.js` bare overskrive den tomme `src` og fjerne `data-src` når det er tid til at hente billedet.

**Comment by Mortal** [comment]
Vil en tom `src` ikke bare svare til at hente dokumentet selv som billede?

Dvs. `<img src="" />` på `http://example.com/foo/bar.html` vil prøve at vise `http://example.com/foo/bar.html` som et billede... Ligesom når man sætter `<form action="">`.

**Comment by neic** [comment]
Nej, men `<img src="" data-src="foo" alt="bar" >` er desværre heller ikke valid. Vi kan dog bruge en 1x1px png i base 64. Se https://varvy.com/pagespeed/defer-images.html.

Teknikken hedder desuden 'defer [images]'. Min google-fu fejlede mig tidligere.
