### ISSUE TITLE
Facebook graph info

### ISSUE THREAD

**Issue by neic** [TK-IT/web#38]
På Rizzoma startede en tråd om hvilke billeder der vises når der linkes til (den gamle) hjemmesiden på facebook. Vi bør tilføje de rette tags her.

https://developers.facebook.com/tools/debug/og/object?q=TAAGEKAMMERET.dk

Det skal testes når siden er online.

**Comment by furt11** [comment]
Jeg har tilføjet en opengraph block til base.html-template som indeholder det essentielle i https://github.com/TK-IT/web/commit/32fb50ff530efe42e61275aae7d55e759cf8881f. Vi burde måske undlade og:title og og:url, siden de informationer så vil blive læst fra sidens øvrige html-tags. Det er blot og:image der er vigtig for at det ser ok ud, når folk deler et link på Facebook o.l.
