### ISSUE TITLE
Generelt design (inden vi går live)

### ISSUE THREAD

**Issue by neic** [TK-IT/web#39]
Som siden ser ud nu er bare et simpelt funktionelt design. Det er ikke noget jeg har tænkt nærmere over og det har altid været ment som en placeholder indtil nogen fandt på noget bedere.

Jeg mener at vi skal fokusere på at få erstattet den nuværende side først og fremmest. Vi kan i fremtiden forbedre designet, men det design vi går live med skal være mindst lige så godt som det gamle.

Er der nogen der har nogle indsigelser for at vi går live med det nuværende design?

**Comment by neic** [comment]
Til hackday blev det diskuteret om det skulle være sort-på-hvid eller hvid-på-sort. Hvad blev enden på det? @Mortal @furt11

**Comment by furt11** [comment]
Jeg synes at det skal være et mørkt tema, da det er hvad jeg forbinder med
TK's hjemmeside.
Det skal nok være en mørk(ikke sort) baggrundsfarve, med lys skrift. Jeg
vil gerne bruge lidt tid på at forsøge at gøre det pænt, men jeg har ikke
sat mig ind i less og hvordan det compileres til css. Så andre må gerne
tage opgaven op, hvis de synes less er vigtigt.

man. 2. maj 2016 kl. 16.11 skrev Mathias Dannesbo <notifications@github.com

**Comment by neic** [comment]
Okay. Jeg løser #51 nu. Det vil være spild af tid at finpudse noget CSS.

**Comment by neic** [comment]
Så er der LESS support. @furt11 Gå amok i `static-src/variables.less`. Du kan finde alle variablerne i `static-src/bootstrap/less/variables.less`. Se readme for dokumentation.

**Comment by furt11** [comment]
Jeg har lavet et lille mock-up af styling af galleriet, med mobil og tablet som fokus. Det fungerer dog også fint på desktop. Giv gerne jeres holdning: https://gist.github.com/furt11/62938d8a4cbf907ef8706dfecc9e8e11

**Comment by neic** [comment]
Jeg har lavet et lys-på-mørk tema. Det er bedere end det gamle, men der kan stadig være små fejl. Jeg lukker dette issue nu (I må genåbne hvis I ikke er enig). Jeg laver et nyt issue om ændring af `image.html` da det ikke er nødvendigt at få gjort inden v1.0.
