### ISSUE TITLE
Statiske filer til mail

### ISSUE THREAD

**Issue by neic** [TK-IT/web#41]
Der bliver nogle gange uploaded filer til mail der bliver sendt til hængerlisten. Et eksempel er http://www.TAAGEKAMMERET.dk/kammerkluns-f2015.pdf

Vi skal have en erstatning med den nye hjemmeside. Måske kan vi bruge http://tket.dk

**Comment by furt11** [comment]
At, vi har benyttet _TAAGEKAMMERET.dk_ tidligere, var fordi at det var 'pænt' at linke til vores egen hjemmeside. Men at benytte et andet domæne, som f.eks. _tket.dk_, er for mig ikke specielt meget pænere end et link til f.eks. dropbox. Jeg mener ikke, at vi behøver, at bruge kræfter på det. 

Relateret kunne det da være fint at kunne vedhæfte filer til mails i stedet.

**Comment by neic** [comment]
Ah, så det er kun blevet brugt fordi det med det nuværende system ikke muligt at vedhæfte filer?

**Comment by furt11** [comment]
Ja.

man. 28. mar. 2016 kl. 19.08 skrev Mathias Dannesbo <
notifications@github.com>:

**Comment by neic** [comment]
Så syntes jeg at den rette løsning er at kunne vedhæfte filer i mailsystemet. Efter person databasen er migret, skal vi vel også have lavet en måde at kunne sende mail til hængerlisten på? Er hængerlisten den eneste liste der ikke er et offentligt alias til? Hvad er @Mortal mening?

**Comment by Mortal** [comment]
Hængerlisten er ikke en gruppe i mailsystemet, men en separat søjle i databasen -- så ja, det er den eneste liste man ikke kan skrive til via et mailalias.

Det er en god idé at understøtte vedhæftede filer i mails til hængerlisten, men det er også smart at kunne linke til en uploadet fil, da det tillader at man retter i filen efter mailen er sendt, hvis der f.eks. er fejl i kluns-kataloget. Desuden kan man have lyst til at sende store filer, og så er der båndbredde at spare ved ikke at sende det sammen med filen (men det er nok ikke så vigtigt i virkeligheden).

**Comment by neic** [comment]
Hvis ikke BEST skal bruge SorteVinduer™, hvordan skal vi så håndtere filupload? Der er nogen timers arbejde i at lave en Django app der kan håndtere det via jQuery File Upload. Er det arbejdet værd?

**Comment by furt11** [comment]
Kan der laves et skjult "album" med filerne tilhørende hver bestyrelsesår?

man. 2. maj 2016 kl. 16.16 skrev Mathias Dannesbo <notifications@github.com

**Comment by Mortal** [comment]
Hvis det bare skal håndtere f.eks. klunskataloget og andre filer der udsendes en sjælden gang imellem, behøver vi kun lave en flad liste af uploadede filer. Jeg har lavet noget lignende til https://quiz.cs.au.dk (hvor det af og til er nødvendigt at kunne linke til et billede) -- her er hele koden:

```python
from multiupload.fields import MultiFileField

@python_2_unicode_compatible
class Image(models.Model):
    file = models.FileField()
    created_time = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL,
                                null=True, blank=False)

    def __str__(self):
        return "<Image %s>" % (self.file,)

class ImageForm(forms.Form):
    files = MultiFileField()

    def clean(self):
        files = self.cleaned_data.get('files', [])
        images = []
        for f in files:
            images.append(Image(file=f))
        return {'images': images}

@authorization_required
class ImageList(ListView):
    queryset = Image.objects.all()
    template_name = 'assessment/imagelist.html'

@authorization_required
class ImageCreate(FormView):
    form_class = ImageForm
    template_name = 'assessment/imagecreate.html'

    def form_valid(self, form):
        for i in form.cleaned_data['images']:
            i.creator = self.request.user
            i.save()
        return HttpResponseRedirect(reverse('image_list'))
```

**Comment by Mortal** [comment]
Det er nu implementeret i e3569585b cba36f561.

**Comment by neic** [comment]
Er der nogen grund til dette ikke er lukket?
