### ISSUE TITLE
Fix style på tk-brand

### ISSUE THREAD

**Issue by neic** [TK-IT/web#48]
Efter 703b6be54e967f5db234a6c6bb599526ea049b84 og 60418de619e21f353037da9a8bcbe5ea1fc99a31 er stylen på `.tk-brand` måske blevet bedere på Windows, men på OSX er det en tilbagegang. Det hele er desuden blevet bold.

Ser `font-family: "Courier New", Courier, monospace;` ikke acceptabelt up på Windows og Linux?

På OSX ser det lækkert ud på en HiDPI skærm, men er lidt gnidret på en skærm med 1x DPI. Det er specielt "**A**M**M**E". Jeg kan ændre kerningen lidt.

OSX:
<img width="162" alt="tket courier osx 2xdpi" src="https://cloud.githubusercontent.com/assets/255399/14848348/8d62c73c-0c6d-11e6-99fa-3e7489cfe271.png"> Courier 2xDPI
![tket courier osx 1xdpi](https://cloud.githubusercontent.com/assets/255399/14848351/8d67c714-0c6d-11e6-9341-eae1c9893d02.png) Courier 1xDPI
![tket pt mono osx 1xdpi](https://cloud.githubusercontent.com/assets/255399/14848349/8d6323da-0c6d-11e6-9826-7cc789561ac2.png) PT Mono 1xDPI
![tket pt mono b osx 1xdpi](https://cloud.githubusercontent.com/assets/255399/14848350/8d63955e-0c6d-11e6-94c4-4a66deaf95d6.png) PT Mono Bold 1xDPI

**Comment by furt11** [comment]
Android var vist problemet og grunden til at jeg valgte PT Mono(webfont fra
Google).

ons. 27. apr. 2016 kl. 11.58 skrev Mathias Dannesbo <
notifications@github.com>:

**Comment by furt11** [comment]
Jeg synes, at de enkelte fede **Å A** og **M** ikke er kønne. Men det er måske hvad andre foretrækker? Vi kan også lave en afstemning blandt os eller mange. Herunder er de 9 omtalte varianter i Chrome på Windows. (Chrome render ikke pænt ved min DPI).

<img width="110" alt="tket_pt mono_mixed" src="https://cloud.githubusercontent.com/assets/15422159/14854618/b7fbffc2-0c90-11e6-9271-11a5e9b25d41.PNG">
<img width="113" alt="tket_courier_bold" src="https://cloud.githubusercontent.com/assets/15422159/14854619/b7fc4e96-0c90-11e6-9f8d-99c7c460b38f.PNG">
<img width="111" alt="tket_courier_thin" src="https://cloud.githubusercontent.com/assets/15422159/14854620/b7fc6cdc-0c90-11e6-8748-04186d26dbd6.PNG">
<img width="111" alt="tket_pt mono_thin" src="https://cloud.githubusercontent.com/assets/15422159/14854622/b7fd2a00-0c90-11e6-9cbe-1e3774bdeade.PNG">
<img width="113" alt="tket_pt mono_bold" src="https://cloud.githubusercontent.com/assets/15422159/14854623/b7fd85ae-0c90-11e6-8126-712e6c0ac0b4.PNG">
<img width="111" alt="tket_courier new_bold" src="https://cloud.githubusercontent.com/assets/15422159/14854621/b7fc7934-0c90-11e6-81a8-5ff962cc0b5c.PNG">
<img width="111" alt="tket_courier new_thin" src="https://cloud.githubusercontent.com/assets/15422159/14854624/b8128800-0c90-11e6-8cd5-1fe842f60a0c.PNG">
<img width="108" alt="tket_courier_mixed" src="https://cloud.githubusercontent.com/assets/15422159/14854625/b812f4f2-0c90-11e6-81f0-ef8e3dbf739a.PNG">
<img width="113" alt="tket_courier new_mixed" src="https://cloud.githubusercontent.com/assets/15422159/14854626/b8174fe8-0c90-11e6-9aa4-c1831685c4f3.PNG">

Ang. fontvalg, så er det vel klart at foretrække at finde én serif-monospace-font, som kan benyttes på alle platforme, uden at ty til webfonts.

**Comment by neic** [comment]
Jeg har nu sat `font-family: "Courier New", Courier, monospace;`, fjerne bold, lavet tranformationerne så de skalere med tekststørrelsen samt tilføjet lidt kerning imellem "**A**M**M**E".

Jeg er enig i at de fede bokstaver er for fede. Den rigtige løsning ville være at lave dem semi-bold, men det bliver aldrig godt i CSS. Jeg synes dog at det er bedere at de er fede, end at de ikke er. Hvis vi skal have dem semibold er et SVG logo vejen frem.

Det her ser fint (læs: ens) ud på:
* OSX 2xDPI, Chrome
* iPhone 4 2xDPI, Safari
* Win7 1xDPI, Chrome
* Win7 1xDPI, IE11

Hvis det også ser godt (læs: ligner det jeg ser) på Android, Windows >1xDPI og Linux syntes jeg at vi skal beholde det som det er nu og så erstatte det store logo med en SVG i fremtiden.

**Comment by neic** [comment]
Med 72103ac7abe33c2619d2c012db463943dac51cbe er skalering mellem `.tk-brand` og den almindelige tekst mere ens. Det er også blevet en smule mere læsbart.

**Comment by neic** [comment]
Vi @furt11 teste det på Windows >1xDPI?
og @Mortal teste det på Linux og måske android?

**Comment by furt11** [comment]
<img width="318" alt="tkbrand 2xchromewin" src="https://cloud.githubusercontent.com/assets/15422159/15855113/fe499772-2cad-11e6-8633-73d9d7d0441a.PNG">
Screenshot ved 200% skalering i Chrome på Windows 10. 
Ikke kønt.

**Comment by Mortal** [comment]
Jeg har lagt designet op på http://users-cs.au.dk/rav/tkweb/.

Firefox på Linux:

![tkweb-linux](https://cloud.githubusercontent.com/assets/373639/15856636/0556626c-2cb7-11e6-8439-981595c2a829.png)

Firefox for Android:

![tkweb-android](https://cloud.githubusercontent.com/assets/373639/15856617/ee396d54-2cb6-11e6-8d69-ae279d3c9aa0.png)

**Comment by neic** [comment]
Der ikke findes Courier, Courier New eller en anden ligenden font på Android. Det eneste vi kan gøre er at embedde en font. Jeg har nu embedded Computer Modern Typewriter. Nu ligner det outputtet fra `tket.sty`, men mindre det fra RεmToR. Desuden er de fede bokstaver ikke lige så fede som de var før.

Alt i alt er det eneste dårlige at vi skal loade 138kb mere.

Virker det på Android, Linux og Windows?

**Comment by furt11** [comment]
Det er uheldigt, må være blive sådan indtil videre. Det ser meget bedre ud
på windows med høj dpi nu. /FURT

ons. 8. jun. 2016 kl. 17.30 skrev Mathias Dannesbo <notifications@github.com

**Comment by neic** [comment]
@Mortal Vil du tjekke om det ser nogenlunde sådan her ud på Linux og Android?
![image](https://cloud.githubusercontent.com/assets/255399/16092335/b05e3e9c-3337-11e6-9378-05f924bc8885.png)

**Comment by Mortal** [comment]
Firefox for Android 
<a href="https://cloud.githubusercontent.com/assets/373639/16097635/c637f926-331c-11e6-84af-9600624af227.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/373639/16097635/c637f926-331c-11e6-84af-9600624af227.png" alt="screenshot_2016-06-07-13-49-28" width=400></a>

**Comment by Mortal** [comment]
Eh... Firefox kan ikke finde ud af at eksportere web-fonts med Ctrl-S. Er siden lagt op et sted hvor jeg kan pege min mobiltelefon hen?

**Comment by Mortal** [comment]
Her er et forsøg på at lægge designet op et sted hvor man kan se det på internettet. https://users-cs.au.dk/rav/tkweb-design/bla.html

<a href="https://cloud.githubusercontent.com/assets/373639/16097828/fe932970-331d-11e6-863b-d169006bd059.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/373639/16097828/fe932970-331d-11e6-863b-d169006bd059.png" alt="screenshot_2016-06-15-17-23-41" width=400></a>

**Comment by neic** [comment]
@Mortal Tak. Er Linux også ok?

**Comment by Mortal** [comment]
Det er ok.

![brand-master](https://cloud.githubusercontent.com/assets/373639/16311989/00aee450-3973-11e6-97fc-6e4a2a39efef.png)
