### ISSUE TITLE
Thumbnails og mapper bliver ikke slettet

### ISSUE THREAD

**Issue by neic** [TK-IT/web#56]
Når man sletter et billede (et object der nedarver fra `BaseMedia`), bliver thumbnails ikke slettet på filsystemet. Originalfilerne bliver dog slettet. Dette gælder også når man sletter hele albums.

Desuden forbliver tomme mapper fra et album når alle filer er slettet.

**Comment by neic** [comment]
Venter på https://github.com/respondcreate/django-versatileimagefield/issues/54.

**Comment by Mortal** [comment]
Jeg har fikset respondcreate/django-versatileimagefield#54 i [TK-IT/django-versatileimagefield branch issue-54](https://github.com/TK-IT/django-versatileimagefield/tree/issue-54), og jeg har ændret vores requirements.txt til at bruge denne fork i 8e914a9d9e0928cb4d37ff45a742cf6c68ae70fd.
