### ISSUE TITLE
Større billeder på image.html

### ISSUE THREAD

**Issue by neic** [TK-IT/web#57]
Vi spilder en masse plads på `image.html` lige nu. Vi skal fjerne en masse af marginerne. Jeg tror det er bedst hvis `image.html` ikke nedarver fra `base.html`.

@furt11 har lavet et mockup: https://gist.github.com/furt11/62938d8a4cbf907ef8706dfecc9e8e11

**Comment by furt11** [comment]
På skærme, hvor viewport er højere end bred, hentes ikke store nok portrætbilleder til at fylde den nye template. Især på mobil-skærme er det uheldigt. 
Derfor bør der ændres lidt på hvilke størrelser, der croppes til. Jeg ved det var @neic der sidst har sat sig ind i det _thumbnail_-modul og _img srcset_ og _sizes_.

**Comment by neic** [comment]
Det her er helt galt. Jeg tror det er bedere at du kigger på det igen.

**Comment by furt11** [comment]
Jeg kigger selv på en løsning nu.

**Comment by furt11** [comment]
Da der ikke kan vælges billed-kilde efter `max(vw, vh)`(det er ikke en del af specs.), vil det åbenbart være et problem at hente _store nok_ billeder i det tilfælde, hvor skærmen er højere end bred eller omvendt. 

**En let løsning:**
Billederne kan stadig hentes store nok ved at ændre på grænserne for, hvornår en kilde skal benyttes. Da de fleste mobilskærme har et h/b-forhold tæt på 2, så ender man således med at hente billedet i dobbelt så stor opløsning, som der vises, i det tilfælde hvor billedeformatet og skærmformatet er modsat. 

Eksempel på `srcset`, hvor der hentes for store billeder, når billedet er højdebegrænset, men som fylder siden op, op til et h/b-forhold på 2:
`srcset="{{ file.file.thumbnail.400x400.url }} 200w,
{{ file.file.thumbnail.720x720.url }} 360w,
{{ file.file.thumbnail.940x940.url }} 470w,

{{ file.file.thumbnail.1140x1140.url }} 570w,
					{{ file.file.thumbnail.2280x2280.url }} 1140w"`

Det tager ekstra båndbredde. Kunne måske afhjælpes af tilførelsen af flere forskellige skaleringer, så `src` kan vælges i finere intervaller.


**En træls løsning:**
Alternativt skal vi selv lave en udvælgelsesalgoritme i javascript/jquery, som vælger `src` til billedet afhængigt af viewport-h/b. 

Hvad tænker du, @neic ?

**Comment by furt11** [comment]
Tanketorsk(edit): Vi har sjældent billeder med mere ekstreme proportioner end 16:9, så 16/9 bør selvfølgelig være forholdet mellem hvad der angiver i size og src. Hvis forholdet er mere ekstremt, er der nok tale om et horisontalt panoramabillede og undgår problemer.

**Comment by neic** [comment]
Jeg har ikke kigget i detaljer, men min browser viser flere billeder på samme side og js virker ikke. At den loader et billede der ikke er den rette størrelse er et mindre problem.

Jeg forstår ikke hvorfor det skulle være nødvendigt at ændre andet end et par af de ydre `div` og lidt tilhørende CSS. Hvad er grunden til at du skulle ændre i javascripten, `views.py` og 73 linjer i `image.html`? Det virkede jo før.

**Comment by furt11** [comment]
Prøv at slette din cache? Hvis det er helt ad helvede til kan du bare
fjerne mine commits. Det virker forrygende her.

Den ons. 15. jun. 2016 20.05 skrev Mathias Dannesbo <
notifications@github.com>:

**Comment by neic** [comment]
Hvilken cache?

Se her: https://gfycat.com/DarkUnequaledElectriceel

Desuden mangler der også et stylesheet `tkgal.css`.

**Comment by furt11** [comment]
Kigger på det om en halv time

Den ons. 15. jun. 2016 20.22 skrev Mathias Dannesbo <
notifications@github.com>:
