### ISSUE TITLE
404 "Gå et skridt tilbage og bund en bajer"

### ISSUE THREAD

**Issue by furt11** [TK-IT/web#58]
404-siden er lidt kedelig. Og mon ikke nogen kommer til at ende på den, når den nye side overtager. Jeg foreslår at få nogen til at lave en simpel tegning/billede af en hænger, der bunder en bajer og tekst ala: "Bund en bajer". Hvis det skulle være flot og alt for fint spørger vi f.eks. Hønsemor, om han kunne finde på noget. Hvad tænker I?

Selvfølgelig skal der nok også være en mailadresse til webmaster.

**Comment by furt11** [comment]
Jeg har nævnt det for Hønsemor, og han har vist nogle gode ideer til en illustration, og vil gerne lave en. Jeg har givet ham instruktioner om, at den også skal kunne aftydes på mobilskærm.

**Comment by furt11** [comment]
![13405234_10209820968224929_965714418_o](https://cloud.githubusercontent.com/assets/15422159/15896433/99132fec-2d90-11e6-8fb6-988e4ad4c500.png)
Skitse fra Hønsemor, som jeg synes er helt perfekt! Jeg har foreslået, at han måske kan tilføje en smidt bærbar i baggrunden, så det er en kammer-hænger-koder, der er gået kold. Men jeg har egentlig bare givet ham nogenlunde frit spil - det er ham, der kan det med at tegne ;)

**Comment by furt11** [comment]
Hønsemor har meldt pas til at hjælpe, trods tidligere udmeldinger. Han lyder som en presset mand. 
Gode ideer modtages.

**Comment by neic** [comment]
![tkweb-404-skitse](https://cloud.githubusercontent.com/assets/255399/18413487/6d404cd4-77a9-11e6-8e72-3bfc3d4b4755.png)

Jeg har lige haft skitsen igennem photoshop. Kan vi ikke bruge den som den er?

**Comment by Mortal** [comment]
Jeg synes vi skal have lov af Hønsemor før vi bruger hans skitse.

**Comment by Mortal** [comment]
Vi har fået lov af Hønsemor.

**Comment by Mortal** [comment]
Baggrundsfarven på hjemmesiden er #080808, men baggrunden på billedet ser ud til at være sortere. Kan vi lave det om til PNG med alpha channel?
