### ISSUE TITLE
Tilføj favicon.ico

### ISSUE THREAD

**Issue by neic** [TK-IT/web#6]
Se: https://en.wikipedia.org/wiki/Favicon#HTML5_recommendation_for_icons_in_multiple_sizes

**Comment by furt11** [comment]
Måske dette kan bruges: http://realfavicongenerator.net/favicon?file_id=p1a34qikgm1av514nq1u933f7puc6 (ved ikke hvor lang tid linket er gyldigt). De ser okay pæne ud, når jeg lige tester de forskellige ikoner.

**Comment by furt11** [comment]
Såøh, jeg har åbenbart ikke gennemskuet static-files endnu. :/
