### ISSUE TITLE
Slugify med ae, oe, & aa?

### ISSUE THREAD

**Issue by furt11** [TK-IT/web#62]
Jeg er ked af, at æ, ø & å går tabt i slugs brugt til url'er til albums og flatpages. Er der noget i vejen for at skrive sin egen slugify funktion, med inspiration fra django.utils.text's slugify, og benytte den i stedet for? Det er jo blot at tilføje en regex, der erstatter de tre tegn æ,ø&å med ae,oe,aa, først? 

Det kan godt være det er et dumt spørgsmål, men kom bare til at tænke på det. /FURT

**Comment by neic** [comment]
Der er to slugify funktioner i django. Den ene er `django.utils.text.slugify` som bliver kaldt fra bla. `Image.clean()`.

Den anden er er `urlify.js` som er en del af admin siden. Den bliver bla. kaldt hvis man sætter `prepopulated_fields = { 'slug': ('title',), }`

`django.utils.text.slugify` smider alle ikke ASCII tegn væk hvis man ikke kalder den med `allow_unicode=True` (virker kun i django>=1.9).

`urlify.js` erstatter æ -> ae, ø -> o og å -> a.

`urlify.js` bliver brugt til slugs til `Album`. `django.utils.text.slugify` bliver brugt til slugs til `Image` og `GenericFile`.

`urlify.js` er rodet at gøre noget ved. Til `django.utils.text.slugify` er det nemt at skrive en wrapper funktion med [`unidecode`](https://pypi.python.org/pypi/Unidecode). `unidecode` har samme mapping på æ, ø, å som `urlify.js`.
