### ISSUE TITLE
Rydde op i idm model

### ISSUE THREAD

**Issue by neic** [TK-IT/web#63]
@Mortal og jeg har ændret en del. Der mangler stadig:
- [x] flyt hængerlisten til en gruppe
- [x] ændre ja/nej til bool
- [x] omdøbe fields

**Comment by Mortal** [comment]
By unanimous vote among the people present, I have decided to name the Profile fields as follows:

* name
* email
* street_name
* house_number
* postal_code
* town
* country
* gone
* phone_number

**Comment by Mortal** [comment]
Fixed i idm-branchen.
