### ISSUE TITLE
YAPF

### ISSUE THREAD

**Issue by neic** [TK-IT/web#64]
Hvad siger I til at køre [yapf](https://github.com/google/yapf) på alt python koden?

**Comment by Mortal** [comment]
Det ser ikke ud til at lave særlig pæn kode. Hvis jeg kører den på idm/admin.py får jeg f.eks. følgende diff:

    -    list_display = (
    -        'name', 'regexp', 'matchtest',
    -    )
    +    list_display = ('name',
    +                    'regexp',
    +                    'matchtest', )

Hvert element bør være på en linje for sig selv.

**Comment by neic** [comment]
Jeg har kigget mere på det og er enig i at den laver nogle mærkelige ting nogle steder. Jeg har også forgæves forsøgt at tweake indstillingerne til det bedere. Det er ikke lykkedes at få et godt resultat. [Line breaks er svært](http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/).

Jeg har istedet installeret flake8. I Spacemacs viser alle fejl out of the box. Det burde fange en del af de fejl jeg laver.

**Comment by Mortal** [comment]
flake8 er mega smart -- det burde alle bruge.
