### ISSUE TITLE
Gå live

### ISSUE THREAD

**Issue by neic** [TK-IT/web#74]
Efter en private beta periode skulle vi være klar til at gå online for alvor. Følgende skal ske:
- [x] Fiks alle issues i [Milestone v1.0](https://github.com/TK-IT/web/milestone/4)
- [x] Giv BEST besked om at den gamle persondatabase ikke må røres
- [x] Importer et frisk dump fra den gamle persondatabase
- [x] Flyt mail systemet til at bruge den nye database
- [x] Flyt domæne
  - [x] Send mail til Glad
  - [x] Få svar fra Glad
- [x] Set redirect op fra fh.cs.au.dk
- [x] Apache conf
  - [x] Simpelt http setup
  - [x] HTTPS med letsencrypt
  - [x] HTTPS certificate renewal cronjob på prodekanus (efter vi er gået live)
- [x] Indkommenter `*_COOKIE_SECURE` linjer i `prog.py`. HTTPS først.
- [x] `manage.py check --deploy`

**Comment by furt11** [comment]
> https med letsencrypt.
 Vil vi redirecte http-trafik til https? 
Og ligeledes vil vi redirecte fra www.TAAGEKAMMERET.dk til TAAGEKAMMERET.dk? Jeg stemmer for begge.

Jeg kan ikke umiddelbart se, at der er noget jeg kan hjælpe med, hvis @Mortal tager sig af Letsencrypt- og apache-delen ;)

**Comment by Mortal** [comment]
Ja, vi redirecter HTTP til HTTPS. Mht. www foran har jeg kun en svag holdning for at beholde www, men jeg kan lade mig overtale til det andet...

**Comment by Mortal** [comment]
Jeg har nu lavet et Let's Encrypt-certifikat til beta.tket.dk som en éngangsfornøjelse (som er gyldigt i 3 måneder). Når det rigtige domæne er flyttet sætter jeg et cronjob op på prodekanus til at renewe certifikatet.

**Comment by neic** [comment]
`manage.py check --deploy` giver nu kun følgende og det skulle apache gerne tage sig af. 
```
?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your
MIDDLEWARE_CLASSES so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF,
SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
```

**Comment by Mortal** [comment]
Domænet er flyttet, renew scriptet opdateret, og BEST har fået besked på kun at ændre i den nye persondatabase. Jeg har sat et `tkammer@prodekanus`-cronjob op til at kopiere idm-databasen til pulerau hver nat kl. 5:42.

Vi er live!
