### ISSUE TITLE
Smagsdommeri: Best/FU tabellerne er ikke kønne

### ISSUE THREAD

**Issue by MadsBaggesen** [TK-IT/web#78]
Layoutet af best/fu tabellerne er ikke kønne i mine øjne, pga de hvide streger. Tror de kunne være væsentlig pænere hvis stregerne ikke var der.

![image](https://cloud.githubusercontent.com/assets/15051029/18387277/01f774ec-769c-11e6-8815-fdb9a7a1dafc.png)

**Comment by neic** [comment]
FURT skriver: "Mailadresserne bør næsten right align'es."

**Comment by Mortal** [comment]
Hvad med at bruge streger i #222 ligesom under overskrifter på andre sider?

**Comment by neic** [comment]
Jeg har ændret border til den farve vi bruger til andre streger, lavet tabellen smallere og justeret teksten af emailadresser til højre. Jeg har desuden også skruet ned for linkfarven.
