### ISSUE TITLE
Smagsdommeri: Galleri - link fra toppen til "ældre"

### ISSUE THREAD

**Issue by MadsBaggesen** [TK-IT/web#82]
Når man kommer ind på galleriet er det svært at se at der er ældre mapper.

Måske kunne der være et link til "ældre" end årets når man står i toppen af nyeste år.

**Comment by neic** [comment]
Med #81 kan man klappe det nuværende år sammen istedet. Det giver samme mulighed, dog er knappen ikke så explicit.
