### ISSUE TITLE
Skal scrolle horizontalt for at nå menuen

### ISSUE THREAD

**Issue by MadsBaggesen** [TK-IT/web#87]
På min mobil, på kontakt siden ryger menuen ud til højre så jeg skal scrolle for at se den.

Det sker kun på kontakt siden, og ser ud til at skyldes at logoet nederst på siden nægter at blive smalt nok til at matche content. Det øvrige content har bredde der passer til telefonen, men logoet er cirka 20% for stort.

Min mobil er Z3 compact, med chrome som browser. Jeg kan ikke fremprovokere det samme med min pc chrome selvom jeg gør den minimal i bredden.

**Comment by Mortal** [comment]
På min telefon er logoet på kontakt-siden også for stort (men det rykker af en eller anden grund ikke på menuen) på Firefox, Android.

Skal vi ikke bare sætte max-width:100% på logoet?

**Comment by neic** [comment]
Jeg har lavet billede til `class="img-responsive"`.  Hvordan ser det ud nu? @MadsBaggesen @Mortal

**Comment by Mortal** [comment]
Det ser ud som om billedet resizer til bredden som det skal. (Y)

**Comment by MadsBaggesen** [comment]
Works for me^{TM}

**Comment by furt11** [comment]
Det er nok mig, der har glemt .img-responsive, da jeg flyttede logoet op ved siden af teksten.
