### ISSUE TITLE
Nogle J50-ressourcer giver 404

### ISSUE THREAD

**Issue by spet** [TK-IT/web#88]
Listen over adresser og J50-sangbogen giver 404:

https://beta.tket.dk/J50Resume/J50-Sangbog.pdf
https://beta.tket.dk/j50/Adresser.php
https://beta.tket.dk/j50/.  En side jeg ville forvente havde links men ikke har det.
https://beta.tket.dk/j50/Arrangementer.php
https://beta.tket.dk/J50Resume/J50-Revy.pdf
https://beta.tket.dk/J60/j60brev.pdf

**Comment by neic** [comment]
Sangbogen skal selvfølgelig rettes.

Er der noget værdi i at gemme listen over adresser? 

(Databasen til dem bliver slettet i [idm/migrations/0008_delete_unused_tables.py](https://github.com/TK-IT/web/blob/master/tkweb/apps/idm/migrations/0008_delete_unused_tables.py#L41))

**Comment by spet** [comment]
Altså, jeg bruger dem ikke, men siden alt andet J50 er gemt, så ville det nok være smart at lave en 410 Gone eller en henvisning til J60-adresserne, hvis de da lægges på.

**Comment by neic** [comment]
Vi kan selfølgelig også bare lave en statisk side med dem. Nogen kunne måske finde det interessant at se hvem der var med til j50.

Jeg har også tilføjet to andre J50 sider der ikke er blevet flyttet. Jeg også laver statiske kopier af dem. Der er ikke l link til dem nogen steder fra på den gamle side. Det kan vi lave på den nye side. Se #89.

**Comment by neic** [comment]
J50 adressesiden ser slet ud til at give mening. Der er flere mennesker på som først startede på uni efter 2006. Hvis dataene ikke er rigtige alligevel er der ikke nogen grund til at gemme det.
