### ISSUE TITLE
ShowPicture.php-emulator

### ISSUE THREAD

**Issue by neic** [TK-IT/web#9]
Det skulle være rimelig nemt at emulere `ShowPicture.php`, så gamle links virker.

Ved at gemme et billedes gamle sti i Image modellen, kan `ShowPicture.php`-emulatoren finde den og lave en redirect.

**Comment by furt11** [comment]
Det er en god ide, og jeg tror sku godt jeg kan lave den ;)

**Comment by furt11** [comment]
Da

**Comment by furt11** [comment]
De nuværende URL'er til enkeltbilleder er rimeligt selvforklarende;
http://taagekammeret.dk/Billeder/ShowPicture.php?folder=18-1415/23-Kyndelmissefest&pic_file=20150206-202932.jpg&pic_count=7&mainfoldernr=18&title=Kyndelmissefest&period=14/15#image

Informationerne i 'folder' og 'pic_count' bør have nok information til at vi i det fleste kan vise det korrekte billede. 'folder' indeholder gf-år og album-navn, mens 'pic_count' afhænger af rækkefølgen og dermed også navngivningen af billederne. 

Så egentlig skal vi ikke gemme andet information end gf-år og album-navn på de gamle albums. Dette hører under issue #25 (import af gamle billeder og albums). 

Jeg foreslår dog også, at hvis et billede bliver vist som resultat af at en bruger benytter et gammelt link, så vises der en kort besked om, at det ikke nødvendigvis er det samme billede, som der oprindeligt var linket til. (Det kan vi jo ikke være sikre på, hvis ikke billederne i de oprindelige albums var navngivet med timestamp eller var redigeret). 

Denne mapping fra /Billeder/ShowPicture.php?_____ til det nye galleri færdiggør jeg, når det endelige importscript i issue #25 er færdigt.

**Comment by furt11** [comment]
Desuden: 
Hvis der forsøges at tilgå et billede, hvor 'pic_file' følger formatet ?pic_file=20150206-202932.jpg, kan timestamp herfra benyttes til at verificere/finde det korrekte billede udfra den udlæste EXIF-timestamp.

**Comment by Mortal** [comment]
Er det ikke tilstrækkeligt bare at bruge de samme filnavne som på den gamle hjemmeside? Jeg tænker at det er smart nok i filsystemet at have forskellige albums billeder i forskellige mapper.

**Comment by furt11** [comment]
Ah, jo! Jeg havde tænkt at original-billederne, altså dem i 'Orignale' mapperne, ikke havde de rigtige filnavne i forhold til de skalerede, som bliver vist på siden. 

Men ja, da det gamle rename.sh-script omdøber de originale, så er der selvfølgelig ikke noget problem i at gemme de originale filnavne i image-modellen. Vi kan måske endda blot bruge filnavne fra de originale billeder (uden jpg) i de nye url'er i stedet for de slugs, som bruges pt., hvis filnavne er unikke for billeder i samme album.

**Comment by Mortal** [comment]
Desuden mener jeg at vi bør beholde originale filnavne ved upload (og ved import fra gammel hjemmeside). Så burde slugs være næsten overflødige, ikke sandt?

**Comment by furt11** [comment]
Jo, egentligt. Men hvad skal vi vise i url'en?

**Comment by Mortal** [comment]
Det originale filnavn...?

**Comment by furt11** [comment]
Altså de originale inkl. ".jpg"? Med store bogstaver, hvad hvis der er mellemrum, fjollede tegn, osv.?

**Comment by Mortal** [comment]
Mellemrum burde ikke være et problem; fjollede tegn burde blive håndteret af Django. Tutorhjemmesiden (som pt. kører Python 2) har problemer med uploads for filnavnet ikke er ASCII (noget med encodings), men det burde ikke være et problem i Python 3.

**Comment by neic** [comment]
Jeg har delt diskussionen op da der er tre ting her som kun delvis afhængige:
- Hvordan billederne bliver gemt i filsystemet.
 - Se #27
- Hvordan (den nye) URL ser ud.
 - Se #28
- Hvordan får lavet ShowPicture.php-emulatoren.
 - Denne tråd.

**Comment by neic** [comment]
På den gamle hjemmeside _kan_ der være to filnavne knyttet til et billede:
- Det navn som uploaderen har givet. Det er typisk det navn som kameraet har givet billedet. Eks: `DSC_2342.jpg`, `IMG_0001.jpg`
- Det navn som `rename.sh` har givet billedet ud fra exif-data. Eks. `20150206-202932.jpg`

Er vi sikker på at `Originale` altid indeholder det samme filnavn som bliver brugt i (de gamle) links?

**Comment by neic** [comment]
Dette virker, så længe billederne er sorteret som i det gamle system. Det er ikke tilfældet nu. Se https://github.com/TK-IT/web/issues/25#200053465.

**Comment by neic** [comment]
Hvis et billede bliver slettet virker redirect ikke mere da indekset vil blive ændret. Det var dog også tilfældet på den gamle side. Det betyder at de links (til den gamle side) der er lavet før et billede blev slettet (på enten den nye eller gamle side) ikke peger på det brugeren ønsker.

Links til den nye side er ikke berørt: de peger altid på samme billede uanset om der bliver slettet eller ej.

Jeg mener dette er sådan et lille problem at vi kan ignorere det.

**Comment by furt11** [comment]
Med et import-script kunne vi tilføje den ur, som billedet må formodes at have haft på den gamle side, til django-modellen for billedet (bestemt ud fra den gamle filstruktur). 
Det ville også være mere robust og give mulighed for at genoverveje filstrukturen, hvis det var ønskværdigt. Men det er nok for meget, at gøre ud af det.

**Comment by neic** [comment]
Problemet er at url også ændre sig på den gamle side når der bliver slettet billeder. Den nye url og den nye filstruktur er ikke afhængige af hindanden. Vi kan ikke rigtig gøre noget ved de slettede billeder fra den gamle side: URLerne er allerede i stykker. #42 er dog svaret på bl.a. at slette filer fra den nye side :) Så bliver det ikke værre end det er nu.
