### ISSUE TITLE
Sortering af albums

### ISSUE THREAD

**Issue by furt11** [TK-IT/web#90]
Jeg har lige prøvet at tilføje et album med billeder fra noget TK-E d. 7. maj 2016. Albummet ligger sig, som det første i bestyrelsesåret 15/16. Jeg tænker, at albums skal sorteres kronologisk, med mindre, de er generelle for hele bestyrelsesåret.

https://beta.tket.dk/galleri/

**Comment by neic** [comment]
Problemet er når `oldFolder` er den den tomme streng, bliver det sorteret før de andre. Det nemmeste er nok bare at sætte `oldFolder`på de sidste par album i 15/16. Det bliver ikke et problem med album fra efter GF.

Jeg har sat TK-E albummets `oldFolder = "19-1516/34-Dette-album-er-ikke-importeret-med-scriptet"`.
