### ISSUE TITLE
Video optaget på højkant

### ISSUE THREAD

**Issue by martinsand** [TK-IT/web#91]
Hvis der tilføjes video optaget på 'højkant'/i portræt, så strækkes det. Generelt bryder jeg mig ikke om, at video strækkes for at passe til et bestemt højde/bredde forhold. Se https://beta.tket.dk/galleri/2015/tk-e/2016-05-07-173427.mp4 .

Vi kan godt blive enige om, at man bør optage video horisontalt. Men vi bør imødekomme at ikke alt bliver optaget således.

**Comment by neic** [comment]
Problemet er ikke at vores css ikke kan håndtere det. Problemet er at ihvertfald Chrome ikke tager sig rigtigt af `displaymatrix: rotation of -90.00 degrees` i videoen. Ifølge [det SO spørgsmål](http://stackoverflow.com/questions/29152777/mp4-videos-in-firefox-and-ie-not-respecting-rotation) er det eneste rigtige at gøre at smide videoerne igennem ffmpeg.

(Firefox skulle [fixe det](https://bugzilla.mozilla.org/show_bug.cgi?id=1228601) i version 49 som udkommer om et par uger.)

**Comment by neic** [comment]
Det var [en bug i chrome 52](https://bugs.chromium.org/p/chromium/issues/detail?id=632624). Det er fixet i 53 som udkom for et par uger siden. 
Det virker som det skal i Safari 9.1.3 OSX, Chrome 53.0.2785.116 OSX, Safari iOS 9. I firefox er videoen de rigtige propertioner, men roteret forkert. Det bliver som sagt fixet i [fixet i version 49](https://bugzilla.mozilla.org/show_bug.cgi?id=1228601).
