### ISSUE TITLE
Galleri ordning: oldFolder vs. publish_date

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#97]
Jeg har lige uploadet nogle billeder fra TK-Open, men albummet bliver vist som det første på https://beta.tket.dk/galleri/, før alle de albums der er blevet importeret fra den gamle hjemmeside. Det skyldes at Album har `ordering = ['gfyear', '-eventalbum', 'oldFolder', 'publish_date']`, og det nye album har ingen "oldFolder".

**Comment by neic** [comment]
Det her er duplicate af #90. En nem løsning er at sætte `oldFolder` for de sidste par album inden GF. Efter GF er det ikke noget problem når der ikke er nogen album i det nye år der har `oldFolder` sat.
