### ISSUE TITLE
Udvælge billeder i album inden offentliggørelse

### ISSUE THREAD

**Issue by Mortal** [TK-IT/web#98]
Vil vi understøtte at man kan uploade alle billeder til et nyt album i galleriet og så udvælge de gode billeder inden albummet offentliggøres?

Jeg troede naivt at jeg kunne sætte publish_date til en dato i fremtiden, og så ville albummet være skjult indtil den dato, men det er tydeligvis ikke tilfældet med de TK-Open-billeder jeg lige har uploadet.

**Comment by martinsand** [comment]
Jeg stemmer klart for, at billeder kan uploades og så senere udvælges. Det
vil kunne blive nyttigt i forbindelse med nf's LS-upload.

En anden funktion jeg havde overvejet var brugeruploads af billeder fra
arrangementer. Der bliver taget mange billeder med folks telefoner, som
aldrig bliver gemt af TK, fordi det er for besværligt at sende dem til BEST
osv. (En fremtids-ønsketing fra min side).  /FURT

tor. 15. sep. 2016 kl. 10.45 skrev Mathias Rav <notifications@github.com>:

**Comment by Mortal** [comment]
Her er en nem måde at implementere det på: Sæt notPublic = True på alle uploadede billeder og udvid https://tket.dk/galleri/ hvis man er logget ind som BEST så man kan vise *alle* billeder og slå notPublic til/fra med en knap (JavaScript + AJAX).

**Comment by martinsand** [comment]
Det er en fin måde at gøre det på.

Det ville være dejligt for BEST, hvis der også var en angivelse af, om det endnu er _ubesluttet_, om billedet skal vises. Eller om der aktivt er en anden, der har skjult det. 

Det vil gøre det muligt at beskrive hvert album med "_n_ synlige, _m_ skjult, _k_ nye billeder", i album oversigten når man er logget ind med de rigtige rettigheder. Hvilket igen vil gøre det nemmere senere hen, at udvide funktionaliteten til at tillade brugeruploads af billeder til albums, som så skal godkendes af BEST, før de vises i albummet.

**Comment by Mortal** [comment]
Pt. har 56 af 750 albums på hjemmesiden billeder der er skjult, og i disse albums er det i alt 2181 af 7259 billeder der er skjult.

De fleste skjulte billeder er formentlig almindelig frasortering, men der kan også være billeder der er skjult fordi folk på billederne har bedt om at få dem fjernet. Det kunne være rart at have en måde at angive om der er en særlig årsag til at billedet er skjult.

Hvad med følgende fire valgmuligheder for hvert billede?

* Synligt
* Skjult (fravalgt)
* Skjult, årsag: (fritekst-felt)
* Ubesluttet

Man kunne også forestille sig et ønske om at lave andre tags på billeder i et album, hvis f.eks. en mindre delmængde af billederne skal udvælges til et bestemt formål (protokol, Facebook, ...).

Jeg lagde et commit op på [branch set_visibility](https://github.com/TK-IT/web/tree/set_visibility) den anden dag, men jeg nåede ikke så langt da jeg havde problemer med at sætte et dev environment op.

```
# Antal albums med skjulte billeder
>>> len(set(BaseMedia.objects.filter(notPublic=True).order_by().values_list('album')))
56
# Total antal albums
>>> Album.objects.count()
750
# Total antal billeder i albums der indeholder skjulte billeder
len(set(BaseMedia.objects.filter(
    album_id__in=BaseMedia.objects.filter(notPublic=True).values_list('album')
).values_list('id')))
7259
# Antal skjulte billeder
>>> BaseMedia.objects.filter(notPublic=True).count()
2181
```

**Comment by neic** [comment]
Er det her ikke lukket af #136 ?

**Comment by Mortal** [comment]
Jo, det her er implementeret og deployet for længst.
